version: 2.1
orbs:
  node: circleci/node@3.0.0
  
jobs:
  build:
    working_directory: ~/majorproject-5-wed-16-30-6/FrontEnd
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout:
          path: ~/majorproject-5-wed-16-30-6
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          app-dir: ~/majorproject-5-wed-16-30-6/FrontEnd
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: Run Tests
          command: npm test
  
workflows:
  node-tests:
    jobs:
      - build